# Generated by Django 6.0.7 on 2026-07-19 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('n5', 'N5 — Beginner'), ('n4', 'N4 — Elementary'), ('n3', 'N3 — Intermediate'), ('n2', 'N2 — Upper Intermediate'), ('n1', 'N1 — Advanced')], default='n5', max_length=2)),
                ('daily_goal_minutes', models.PositiveIntegerField(default=15)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('preferred_language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
