# Generated by Django 6.0.7 on 2026-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=5)),
                ('romaji', models.CharField(max_length=10)),
                ('kana_type', models.CharField(choices=[('hiragana', 'Hiragana'), ('katakana', 'Katakana')], max_length=10)),
                ('group', models.CharField(choices=[('a-row', 'A Row (あ行)'), ('ka-row', 'Ka Row (か行)'), ('sa-row', 'Sa Row (さ行)'), ('ta-row', 'Ta Row (た行)'), ('na-row', 'Na Row (な行)'), ('ha-row', 'Ha Row (は行)'), ('ma-row', 'Ma Row (ま行)'), ('ya-row', 'Ya Row (や行)'), ('ra-row', 'Ra Row (ら行)'), ('wa-row', 'Wa Row (わ行)'), ('n-row', 'N Row (ん)')], max_length=10)),
                ('stroke_order_image', models.ImageField(blank=True, null=True, upload_to='kana/strokes/')),
                ('audio_url', models.FileField(blank=True, null=True, upload_to='kana/audio/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within group')),
            ],
            options={
                'ordering': ['kana_type', 'order'],
                'unique_together': {('character', 'kana_type')},
            },
        ),
    ]
