# Generated by Django 6.0.7 on 2026-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. は (wa) — Topic Marker', max_length=200)),
                ('explanation', models.TextField(help_text='Detailed English explanation')),
                ('structure', models.CharField(help_text='e.g. [Noun] は [Noun] です', max_length=300)),
                ('jlpt_level', models.CharField(choices=[('n5', 'N5'), ('n4', 'N4'), ('n3', 'N3'), ('n2', 'N2'), ('n1', 'N1')], db_index=True, max_length=2)),
                ('example_sentences', models.JSONField(default=list, help_text='List of {"japanese": "...", "romaji": "...", "english": "..."}')),
                ('difficulty_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['jlpt_level', 'difficulty_order'],
            },
        ),
    ]
