# Generated by Django 6.0.7 on 2026-07-19 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('kana', 'Kana'), ('kanji', 'Kanji'), ('grammar', 'Grammar')], max_length=20)),
                ('content_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('reviewing', 'Reviewing'), ('mastered', 'Mastered')], default='new', max_length=20)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5, help_text='SRS ease factor')),
                ('interval_days', models.PositiveIntegerField(default=0, help_text='Current SRS interval in days')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
