# Generated by Django 6.0.7 on 2026-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=5, unique=True)),
                ('onyomi', models.CharField(blank=True, default='', help_text='Chinese reading (カタカナ)', max_length=100)),
                ('kunyomi', models.CharField(blank=True, default='', help_text='Japanese reading (ひらがな)', max_length=100)),
                ('meaning', models.CharField(max_length=255)),
                ('stroke_count', models.PositiveIntegerField(default=1)),
                ('jlpt_level', models.CharField(choices=[('n5', 'N5'), ('n4', 'N4'), ('n3', 'N3'), ('n2', 'N2'), ('n1', 'N1')], db_index=True, max_length=2)),
                ('stroke_order_image', models.ImageField(blank=True, null=True, upload_to='kanji/strokes/')),
                ('difficulty_order', models.PositiveIntegerField(default=0)),
                ('example_words', models.ManyToManyField(blank=True, related_name='kanji_set', to='vocabulary.vocabulary')),
            ],
            options={
                'verbose_name_plural': 'Kanji',
                'ordering': ['jlpt_level', 'difficulty_order'],
            },
        ),
    ]
