# Generated by Django 6.0.7 on 2026-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(blank=True, max_length=100, null=True)),
                ('kana', models.CharField(max_length=100)),
                ('romaji', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=255)),
                ('jlpt_level', models.CharField(choices=[('n5', 'N5'), ('n4', 'N4'), ('n3', 'N3'), ('n2', 'N2'), ('n1', 'N1')], db_index=True, max_length=2)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('i-adjective', 'い-Adjective'), ('na-adjective', 'な-Adjective'), ('adverb', 'Adverb'), ('particle', 'Particle'), ('counter', 'Counter'), ('expression', 'Expression'), ('pronoun', 'Pronoun'), ('conjunction', 'Conjunction'), ('prefix', 'Prefix'), ('suffix', 'Suffix')], default='noun', max_length=20)),
                ('category', models.CharField(choices=[('greetings', 'Greetings'), ('food', 'Food & Drink'), ('numbers', 'Numbers & Counting'), ('travel', 'Travel & Directions'), ('family', 'Family & People'), ('time', 'Time & Date'), ('weather', 'Weather & Nature'), ('body', 'Body & Health'), ('school', 'School & Education'), ('work', 'Work & Business'), ('shopping', 'Shopping & Money'), ('hobbies', 'Hobbies & Sports'), ('house', 'House & Daily Life'), ('general', 'General')], db_index=True, default='general', max_length=20)),
                ('example_sentence_jp', models.TextField(blank=True, default='')),
                ('example_sentence_en', models.TextField(blank=True, default='')),
                ('audio_url', models.FileField(blank=True, null=True, upload_to='vocabulary/audio/')),
                ('difficulty_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Vocabulary',
                'ordering': ['jlpt_level', 'difficulty_order'],
            },
        ),
    ]
